/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/get-metadata": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header: {
          authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            path: string;
            /** @default {} */
            opts?: {
              /** @default false */
              ai?: boolean;
              /** @default false */
              revalidate?: boolean;
            };
          };
        };
      };
      responses: {
        /** @description Return the scrape */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["get-metadata-response"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    "get-metadata-response":
      | {
          /** @enum {string} */
          status: "pending";
        }
      | {
          /** @enum {string} */
          status: "missing";
        }
      | {
          status: "success" | "revalidating";
          metadata: {
            title: string;
            description: string;
            openGraph: {
              title: string;
              description: string;
            };
            alternates: {
              canonical: string;
            };
          };
        }
      | {
          /** @enum {string} */
          status: "error";
          message: string;
        };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
